### ISSUE TITLE
error when dashboard data is missing

### ISSUE THREAD

**Issue by Lock128** [ChrisIgel/netatmo-api-client#9]
Hey

I am getting this error
```typescript

2024-11-01T05:53:27.631Z	765aed5a-8343-47df-ac8b-64f4e243ce1d	ERROR	Cannot read properties of undefined (reading 'time_utc')
2024-11-01T05:53:27.632Z	765aed5a-8343-47df-ac8b-64f4e243ce1d	ERROR	Error
    at e.<anonymous> (/var/asset-input/node_modules/netatmo-api-client/dist/netatmo-api-client.js:155:31)
    at step (/var/asset-input/node_modules/netatmo-api-client/dist/netatmo-api-client.js:33:23)
    at Object.next (/var/asset-input/node_modules/netatmo-api-client/dist/netatmo-api-client.js:14:53)
    at d (/var/asset-input/node_modules/netatmo-api-client/dist/netatmo-api-client.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
``` 

I assume this happens here:
https://github.com/ChrisIgel/netatmo-api-client/blob/3dd56be3b81eaedfc5028d86ca188f57959b0402/src/station-data-mapper.ts#L72

when the Netatmo API is not returning data for the main dashboard information

**Comment by ChrisIgel** [comment]
do you know when or why this happens? is it only the case for expired tokens?

**Comment by Lock128** [comment]
oh, it happened because my main station did not have wifi for more than 5 hours and then the API expires the "old" data ;)

**Comment by Lock128** [comment]
Thank you!
